# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Huberization
tagline:          'Bastien Huber\s webste'
description:      'The personal website of a French student who wants to build meaningful and ethical services'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Bastien Huber'
  url:            https://twitter.com/bastien_hub

paginate:         5

# Custom vars
version:          2.1.0

links:
  twitter:        https://twitter.com/bastien_hub
  linkedin:       https://www.linkedin.com/in/bastienhuber/
  instagram:      https://www.instagram.com/bastienhub/

gems:             [jekyll-paginate]
